add parameter create_short_label
GSK-Biostatistics/neo4cdisc pull request #12
Opened 2023-01-24 10:30 UTC by WillMcDGSK

@paltusplintus or @JonathanDeacon Please review!
@PranjaliParnerkar FYI
Small PR for [this PBI](https://dev.azure.com/DevOps-RD/Clinical%20Linked%20Data%20Experiments/_sprints/taskboard/Clinical%20Linked%20Data%20Experiments%20Team/Clinical%20Linked%20Data%20Experiments/Sprint%209.6?workitem=991143). It adds a parameter to generate_excel_based_model() that will control the creation of short_label property on relationships.

2023-01-26 09:19 UTC, JonathanDeacon commented on cdisc_model_managers/cdisc_model_manager.py
> +           SET v.shot_label = CASE WHEN $short_label_bool
Typo: `v.shot_label`, should be `v.short_label`

2023-01-26 09:25 UTC, JonathanDeacon requested changes
Spotted a few minor typos. I'm also a bit confused by the PBI which mentioned "disable creation of short_label on Relationship nodes" specifically? Probably best to double check with  @paltusplintus

2023-01-26 09:25 UTC, JonathanDeacon commented on cdisc_model_managers/cdisc_model_manager.py
> +        :param create_term_indexes: Whether to create the short_label property on Relationship (Variable) nodes
Typo: Should be `:param create_short_label: `

2023-01-26 09:25 UTC, JonathanDeacon commented on cdisc_model_managers/cdisc_model_manager.py
> +           SET v.shot_label = CASE WHEN $short_label_bool
Typo: `v.shot_label`, should be `v.short_label`

2023-01-26 09:32 UTC, WillMcDGSK commented
> Spotted a few minor typos. I'm also a bit confused by the PBI which mentioned "disable creation of short_label on Relationship nodes" specifically? Probably best to double check with @paltusplintus

When we load data in the via the model manager's `generate_excel_based_model()` sometime the variables become relationships instead of classes. In this case they would also have the same properties as classes including short_label, which causes other issues down the line. We don't need the short_label prop on the relationships nodes, so we can just not add them here. 
I have realized that I also included this change to the 'Create Class from Variable' section as well, which was a mistake! I will remove that now.

2023-01-27 08:29 UTC, JonathanDeacon commented
> @JonathanDeacon When we load data in the via the model manager's `generate_excel_based_model()` sometime the variables become relationships instead of classes. In this case they would also have the same properties as on classes including short_label, which causes other issues down the line. We don't need the short_label prop on the relationships nodes, so we can just not add them here. I have realized that I also included this change to the 'Create Class from Variable' section as well, which was a mistake! I will remove that now.

@WillMcDGSK Oh that makes sense! I was confused at first why the changes were in create class from variable and create relationship from variable so I assumed the PBI hadn't been updated.

2023-02-01 11:20 UTC, JonathanDeacon approved these changes
Looks good!

2023-02-01 11:20 UTC, merged